### ISSUE TITLE
How can we extend this library to include a reporter to openTSDB

### ISSUE THREAD

**Issue by tonyvu2014** [omergertel/pyformance#28]
I want to use the metrics and MetricsRegistry from this library and push the metrics to openTSDB. However, the metric only has a key which is not able to support tags from openTSDB. In that case, how can we create an OpenTSDBReporter which is similar to HostedGraphiteReporter for graphite? Thanks.

**Comment by lght** [comment]
You should have a look at pull request #29

**Comment by omergertel** [comment]
Thanks!

**Comment by tonyvu2014** [comment]
Thanks
