### ISSUE TITLE
Requesting new release to pip

### ISSUE THREAD

**Issue by RyanLassigBanks** [omergertel/pyformance#43]
Hi,

Recently there were some fixes for the InfluxDB reporter added to Pyformance. However, these changes don't seem to be present in the version of Pyformance available via pip (0.3.4). I was hoping you could do a new release so we wouldn't have to install the latest code from Github.

Thanks!

**Comment by omergertel** [comment]
Yeah, I'll try to get to it in the next few days. I'm not working with python right now, so I wasn't as attentive as I need to be :)

**Comment by ddavtian** [comment]
@omergertel please release to pip

**Comment by omergertel** [comment]
Done
