### ISSUE TITLE
Tested in Docker?

### ISSUE THREAD

**Issue by ddavtian** [omergertel/pyformance#46]
Hello,

General question here, but has the code been tested with docker containers?

**Comment by omergertel** [comment]
I'm not sure what you mean. What are you concerned about?

**Comment by ddavtian** [comment]
@omergertel wanted to see if there would be any issues say the `OpenTSDBReporter` reporter from within docker, meaning would the threading work properly and fire every `reporting_interval` ?

**Comment by ddavtian** [comment]
@omergertel did additional testing this morning, this part of the testing is not Docker specific but rather I can the code within Gunicorn with the following set of flags

`--bind 0.0.0.0:8000 --timeout 120 --workers 1 --preload --access-logfile - --log-level info octo.wsgi`

Seems like the following loop doesn't trigger on the second interval.

reporter.py

```
    def _loop(self):
        while not self._stopped.is_set():
            try:
                self.report_now(self.registry)
            except:
                pass
            time.sleep(self.reporting_interval)
        # self._stopped.clear()
```

**Comment by ddavtian** [comment]
@omergertel found my issue, closing this ticket and possibly this might help someone else in the future. Seems like when passing `--preload` to Gunicorn it caused the issue for the scheduler not to run.

**Comment by omergertel** [comment]
Thanks, sorry I couldn't help more. Happy you found out your issue 😺

**Comment by ddavtian** [comment]
@omergertel I think I spoke too soon :-(

In a docker container this loop never runs twice. Tested outside of docker in Gunicorn and it works, but same Gunicorn with the same config seems not happy

```
    def _loop(self):
        while not self._stopped.is_set():
            try:
                self.report_now(self.registry)
            except:
                pass
            time.sleep(self.reporting_interval)
        # self._stopped.clear()
```
