### ISSUE TITLE
Possible to add a tag on the commit that was released as 0.4.0?

### ISSUE THREAD

**Issue by quodlibetor** [omergertel/pyformance#48]
Thanks for the release! I was confused because I normally check the [releases page](https://github.com/omergertel/pyformance/releases) for updates and didn't see it there. It also makes it easier to view a list of changed commits from the github UI.

Looks like it was probably https://github.com/omergertel/pyformance/commit/f2c8459b42ce222b1c5d9be4ffc0e06949e64fca

**Comment by omergertel** [comment]
Sure

**Comment by quodlibetor** [comment]
Thanks!
