### ISSUE TITLE
README examples don't work

### ISSUE THREAD

**Issue by emmett9001** [omergertel/pyformance#7]
I'm trying to run the examples in the README file, and they're not working. This is a gist illustrating the issues I'm having (after `pip install pyformance` in a fresh virtualenv):

https://gist.github.com/emmett9001/2b8fd7d09220deb7d16c

Gist line 9: the output is 0, it should be close to 0.1
line 12: `import` fails
line 20: digging through the code, I tried this import, which works
line 37: running this example causes a `NoneType` error.

Am I using an outdated version of pyformance? Is there some fork that is more up to date?

**Comment by omergertel** [comment]
Sorry, can't reproduce.
